
package br.com.layonvsg.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServicoWebImportacaoNegocio", targetNamespace = "http://ws.layonvsg.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicoWebImportacaoNegocio {


    /**
     * 
     * @param localizacao
     * @return
     *     returns java.util.List<br.com.layonvsg.ws.Log>
     */
    @WebMethod
    @WebResult(name = "logs", targetNamespace = "")
    @RequestWrapper(localName = "importarApartirDe", targetNamespace = "http://ws.layonvsg.com.br/", className = "br.com.layonvsg.ws.ImportarApartirDe")
    @ResponseWrapper(localName = "importarApartirDeResponse", targetNamespace = "http://ws.layonvsg.com.br/", className = "br.com.layonvsg.ws.ImportarApartirDeResponse")
    public List<Log> importarApartirDe(
        @WebParam(name = "localizacao", targetNamespace = "")
        String localizacao);

}
