
package br.com.layonvsg.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServicoWebImportacaoNegocioBeanService", targetNamespace = "http://ws.layonvsg.com.br/", wsdlLocation = "http://localhost:8081/apurefx-extrator/ServicoWebImportacaoNegocio?wsdl")
public class ServicoWebImportacaoNegocioBeanService
    extends Service
{

    private final static URL SERVICOWEBIMPORTACAONEGOCIOBEANSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.layonvsg.ws.ServicoWebImportacaoNegocioBeanService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.layonvsg.ws.ServicoWebImportacaoNegocioBeanService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/apurefx-extrator/ServicoWebImportacaoNegocio?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/apurefx-extrator/ServicoWebImportacaoNegocio?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICOWEBIMPORTACAONEGOCIOBEANSERVICE_WSDL_LOCATION = url;
    }

    public ServicoWebImportacaoNegocioBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoWebImportacaoNegocioBeanService() {
        super(SERVICOWEBIMPORTACAONEGOCIOBEANSERVICE_WSDL_LOCATION, new QName("http://ws.layonvsg.com.br/", "ServicoWebImportacaoNegocioBeanService"));
    }

    /**
     * 
     * @return
     *     returns ServicoWebImportacaoNegocio
     */
    @WebEndpoint(name = "ServicoWebImportacaoNegocioPort")
    public ServicoWebImportacaoNegocio getServicoWebImportacaoNegocioPort() {
        return super.getPort(new QName("http://ws.layonvsg.com.br/", "ServicoWebImportacaoNegocioPort"), ServicoWebImportacaoNegocio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoWebImportacaoNegocio
     */
    @WebEndpoint(name = "ServicoWebImportacaoNegocioPort")
    public ServicoWebImportacaoNegocio getServicoWebImportacaoNegocioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.layonvsg.com.br/", "ServicoWebImportacaoNegocioPort"), ServicoWebImportacaoNegocio.class, features);
    }

}
